<?php

/*
Plugin Name: CellarWeb User Profile Access Control
Plugin URI: http://cellarweb.com/wordpress-plugins/
Description: Adds a field to the user profile page to enable banning that user from editing/changing their user profile. User profile edit/change is allowed for roles that have 'edit-user' (administrator, etc). Profile choice not shown in admin pages, even direct access is blocked.
Version: 1.01
Tested up to: 6.3
Requires at least: 4.9
PHP Version: 7.2
Author: Rick Hellewell - CellarWeb.com
Author URI: http://CellarWeb.com
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
 */

/*
Copyright (c) 2016-2022 by Rick Hellewell and CellarWeb.com
All Rights Reserved

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License, version 2, as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA02110-1301USA

 */
//------------------------------------------------------------------------------
// GETTING STARTED start
//------------------------------------------------------------------------------
if (!defined('ABSPATH')) {
	return;
}
define("CWUPAC_VERSION", "1.01 (7 Apr 2022)");

// check for required versions of WP and PHP
$min_wp  = '4.9.6';
$min_php = '7.2';
// check for meeting minimum requirements, disable and notify
if (!CWUPAC_is_requirements_met($min_wp, $min_php)) {
	add_action('admin_init', 'CWUPAC_disable_plugin');
	add_action('admin_notices', 'CWUPAC_show_notice_disabled_plugin');
	add_action('network_admin_init', 'CWUPAC_disable_plugin');
	add_action('network_admin_notices', 'CWUPAC_show_notice_disabled_plugin');
	CWUPAC_deregister();
	return;
}
// ----------------------------------------------------------------------------
// disable plugin if WP/PHP versions are not enough
function CWUPAC_disable_plugin() {
	if (is_plugin_active(plugin_basename(__FILE__))) {
		deactivate_plugins(plugin_basename(__FILE__));
		// Hide the default "Plugin activated" notice
		if (isset($_GET['activate'])) {
			unset($_GET['activate']);
		}
	}
}

// ----------------------------------------------------------------------------
// show notice that plugin was deactivated because WP/PHP versions not enough
function CWUPAC_show_notice_disabled_plugin() {
	echo esc_html__('<div class="notice notice-error is-dismissible"><h3><strong>CellarWeb Server Side Analytics</strong></h3><p> cannot be activated - requires at least WordPress 4.6 and PHP 5.4.&nbsp;&nbsp;&nbsp;Plugin automatically deactivated.</p></div>');
	return;
}

// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// check if at least WP 4.6 and PHP version at least 5.3
// based on https://www.sitepoint.com/preventing-wordpress-plugin-incompatibilities/
function CWUPAC_is_requirements_met($min_wp = '4.6', $min_php = '5.4') {
	// Check for WordPress version
	if (version_compare(get_bloginfo('version'), $min_wp, '<')) {
		return false;
	}
	// Check the PHP version
	if (version_compare(PHP_VERSION, $min_php, '<')) {
		return false;
	}
	return true;
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class CellarWebUserProfileAccessControl {
	private $cellarweb_upac_options;

	public function __construct() {
		add_action('admin_menu', array($this, 'cellarweb_upac_add_plugin_page'));
		add_action('admin_init', array($this, 'cellarweb_upac_page_init'));
	}

	public function cellarweb_upac_add_plugin_page() {
		add_options_page(
			'CellarWeb User Profile Access Control', // page_title
			'CellarWeb User Profile Access Control', // menu_title
			'manage_options', // capability
			'cellarweb-user-profile-access-control', // menu_slug
			array($this, 'cellarweb_upac_create_admin_page') // function
		);
	}

	// modify for plugin header graphic and instructions
	//  adjust divs for sidebar, like in CWUPAC
	public function cellarweb_upac_create_admin_page() {
		$this->cellarweb_upac_options = get_option('cellarweb_upac_option_name');?>

<div >
    <div class="CWUPAC_options">
        <?php CWUPAC_info_top();?>
            <form method="post" action="options.php">
                <?php
settings_fields('cellarweb_upac_option_group');
		do_settings_sections('cellarweb-user-profile-access-control-admin');
		submit_button();
		?>
            </form>
                <?php CWUPAC_footer(); // display bottom info stuff   ?>
</div>
            </div>
    <div class='CWUPAC_sidebar'>
        <?php CWUPAC_sidebar();?>
    </div>
    <?php }

	public function cellarweb_upac_page_init() {
		// get the styles file
		wp_register_style('CWUPAC_namespace', plugins_url('/css/settings.css', __FILE__), array(), CWUPAC_VERSION);
		wp_enqueue_style('CWUPAC_namespace'); // gets the above css file in the proper spot
		// start the settings stuff
		register_setting(
			'cellarweb_upac_option_group', // option_group
			'cellarweb_upac_option_name', // option_name
			array($this, 'cellarweb_upac_sanitize') // sanitize_callback
		);

		add_settings_section(
			'cellarweb_upac_setting_section', // id
			'Settings', // title
			array($this, 'cellarweb_upac_section_info'), // callback
			'cellarweb-user-profile-access-control-admin' // page
		);

		add_settings_field(
			'cwupac_profile_block', // id
			'Enable User Profile Block', // title
			array($this, 'cwupac_profile_block_callback'), // callback
			'cellarweb-user-profile-access-control-admin', // page
			'cellarweb_upac_setting_section' // section
		);

		add_settings_field(
			'cwupac_send_notice', // id
			'Email Admin on Profile Change', // title
			array($this, 'cwupac_send_notice_callback'), // callback
			'cellarweb-user-profile-access-control-admin', // page
			'cellarweb_upac_setting_section' // section
		);
	}

	public function cellarweb_upac_sanitize($input) {
		$sanitary_values = array();
		if (isset($input['cwupac_profile_block'])) {
			$sanitary_values['cwupac_profile_block'] = $input['cwupac_profile_block'];
		}

		if (isset($input['cwupac_send_notice'])) {
			$sanitary_values['cwupac_send_notice'] = $input['cwupac_send_notice'];
		}

		return $sanitary_values;
	}

	public function cellarweb_upac_section_info() {
	}

	public function cwupac_profile_block_callback() {
		printf(
			'<input type="checkbox" name="cellarweb_upac_option_name[cwupac_profile_block]" id="cwupac_profile_block" value="cwupac_profile_block" %s> <label for="cwupac_profile_block">Adds field to user profile screen to allowing blocking that user from their user profiled. Will not modify an administrator\'s profile screen.</label>',
			(isset($this->cellarweb_upac_options['cwupac_profile_block']) && $this->cellarweb_upac_options['cwupac_profile_block'] === 'cwupac_profile_block') ? 'checked' : ''
		);
	}

	public function cwupac_send_notice_callback() {
		printf(
			'<input type="checkbox" name="cellarweb_upac_option_name[cwupac_send_notice]" id="cwupac_send_notice" value="cwupac_send_notice" %s> <label for="cwupac_send_notice">Sends an email to site administrator whenever a user changes their profile, including a password change. Note that the email will contain the contents of all fields, including possible sensitive information, such as when the password has changed. Ensure that the recipient (the site admin) will be responsible in handling that information.</label>',
			(isset($this->cellarweb_upac_options['cwupac_send_notice']) && $this->cellarweb_upac_options['cwupac_send_notice'] === 'cwupac_send_notice') ? 'checked' : ''
		);
	}
}
if (is_admin()) {
	$cellarweb_upac = new CellarWebUserProfileAccessControl();
}

/*
 * Retrieve this value with:
 * $cellarweb_upac_options = get_option( 'cellarweb_upac_option_name' ); // Array of All Options
 * $cwupac_profile_block = $cellarweb_upac_options['cwupac_profile_block']; // CWUPAC_enable_profile_block
 * $cwupac_send_notice = $cellarweb_upac_options['cwupac_send_notice']; // CWUPAC_send_profile_notice
 */

// ----------------------------------------------------------------------------

/* This section do all the work
- adds a checkbox on user profile screen to ban access if not role=edit_user
- adds limitations on user profile visibility
- only shows checkbox user profile for role=edit_user
- based on https://wordpress.stackexchange.com/a/141746/29416

- 25 Mar 2022 - CellarWeb.com
 */
// --------------------------------------------------------------------------------------
// add checkbox to use profile to not allow user access to profile - only administrator role can access
// add_actions based on plugin option settings
$options = get_option('cellarweb_upac_option_name');

// show 'ban user' option on the user profile page
$block_status = (isset($options['cwupac_profile_block'])) ? true : false;

if ($block_status) {
	add_action('personal_options', 'CWUPAC_profile_ban_field');
	add_action('edit_user_profile_update', 'CWUPAC_profile_ban_field_save');
	// remove profile link from dashboard menu
	add_action('wp_before_admin_bar_render', 'CWUPAC_profile_adminbar_remove');
	add_action('admin_menu', 'CWUPAC_profile_menu_remove');
}

// part 1 : show 'ban user' field on profile page
function CWUPAC_profile_ban_field(\WP_User $user) {
	$current = wp_get_current_user();
	if (!is_admin() || $user->ID === $current->ID) {
		return;
	}
	// only on admin if logged in
	if (!user_can($current, 'edit_users')) {
		return;
	}
	// only show additional field for edit-user ability
	$target = new WP_User($user->ID);
	if ($target->exists() && !user_can($target, 'edit_users')) {
		$banned = (int) get_user_meta($user->ID, '_profile_banned', TRUE);
		?>
    <table class="form-table"><tbody><tr>
    <th scope="row">Profile Ban</th><td>
    <input<?php checked(1, $banned);?> name="_profile_banned" value="1" type="checkbox">
   If checked, will block this user from looking at or modifying their user profile. (Via the activated CellarWeb User Profile Access Control plugin.)
    </td></tr></tbody></table>
    <?php
}
}

// --------------------------------------------------------------------------------------

function CWUPAC_profile_ban_field_save($userid) {
	$current = wp_get_current_user();
	if (!is_admin() || $userid === $current->ID) {
		return;
	}

	if (!user_can($current, 'edit_users')) {
		return;
	}

	$target = new WP_User($userid);
	if (!$target->exists() || user_can($target, 'edit_users')) {
		return;
	}

	$ban = filter_input(INPUT_POST, '_profile_banned', FILTER_SANITIZE_NUMBER_INT);
	if ((int) $ban > 0) {
		update_user_meta($userid, '_profile_banned', 1);
	} elseif (get_user_meta($userid, '_profile_banned', TRUE)) {
		delete_user_meta($userid, '_profile_banned');
	}
}

// --------------------------------------------------------------------------------------
// Part 2 - remove profile link from dashboard menu other than administrator

function CWUPAC_profile_menu_remove() {
	$remove = get_user_meta(get_current_user_id(), '_profile_banned', TRUE);
	if (!current_user_can('edit_users') && (int) $remove > 0) {
		remove_menu_page('profile.php');
	}
}

// --------------------------------------------------------------------------------------
// remove profile link from dashboard menu

function CWUPAC_profile_adminbar_remove() {
	$remove = get_user_meta(get_current_user_id(), '_profile_banned', TRUE);
	if ((int) $remove !== 1 || current_user_can('edit_users')) {
		return;
	}

	global $wp_admin_bar;
	$account         = (array) $wp_admin_bar->get_node('my-account');
	$info            = (array) $wp_admin_bar->get_node('user-info');
	$logout          = (array) $wp_admin_bar->get_node('logout');
	$account['href'] = $info['href'] = '#';
	$wp_admin_bar->remove_node('my-account');
	$wp_admin_bar->remove_node('user-info');
	$wp_admin_bar->remove_node('edit-profile');
	$wp_admin_bar->remove_node('logout');
	$wp_admin_bar->add_node($account);
	$wp_admin_bar->add_node($info);
	$wp_admin_bar->add_node($logout);
	// alert that no profile editing allowed via admin bar
	add_action('load-profile.php', 'CWUPAC_profile_banned_check');
}

// --------------------------------------------------------------------------------------
// Part 3 - check if banned, show message indicating profile edit/change not available
// note - plugin settings add_action will happen in function if option enabled

function CWUPAC_profile_banned_check() {
	$remove = get_user_meta(get_current_user_id(), '_profile_banned', TRUE);
	if ((int) $remove === 1 && !current_user_can('edit_users')) {
		add_action('all_admin_notices', 'CWUPAC_profile_banned_msg');
		wp_redirect(admin_url('index.php')); // redirect to admin main page
		exit();
	} else {
		add_action('load-profile.php', 'CWUPAC_profile_banned_check');
	}
}

function CWUPAC_profile_banned_msg() {
	if (current_user_can('edit_users')) {
		return;
	}

	$banned  = (int) get_user_meta(get_current_user_id(), '_profile_banned', TRUE);
	$class   = 'notice notice-error';
	$message = __('Sorry, you are not allowed to edit your profile.');
	printf('<div class="%1$s"><p>%2$s</p></div>', esc_attr($class), esc_html($message));
}

// ----------------------------------------------------------------------------
// notification if user profile changed setting enabled
// ----------------------------------------------------------------------------

function CWUPAC_user_profile_update($user_id) {
	$site_url  = get_bloginfo('wpurl');
	$user_info = get_userdata($user_id);
	$to        = $user_info->user_email;
	$subject   = "Profile Updated on " . $site_url . "";
	$message   = "Hello! The user profile for user " . $user_info->display_name . " has been updated on the $site_url site. The following items have changed:\n\n ";
	foreach ($_POST as $key => $value) {
		$message .= $key . ": " . $value . "\n";
	}
	$message .= "\n\nThis happened at " . date('l jS F Y - h:i:s A');
	wp_mail($to, $subject, $message);
}

$options = get_option('cellarweb_upac_option_name');
// add the action to email if changed profile update set
$sendmail = (isset($options['cwupac_send_notice'])) ? true : false;
if ($sendmail) {add_action('profile_update', 'CWUPAC_user_profile_update', 10, 2);}

// header, footers, sidebars for the settings page
// ----------------------------------------------------------------------------
//  display the top info part of the page
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// supporting functions
// ----------------------------------------------------------------------------
//  display the top info part of the settings page
// ----------------------------------------------------------------------------
function CWUPAC_info_top() {
	?>
<div class="wrap" >
    <h2></h2>
<div align='center' class = 'CWUPAC_header'>
    <div align='center'>
    <img src="<?php echo esc_html__(plugin_dir_url(__FILE__)); ?>assets/banner-1000x200.jpg" width="100%"  alt="" class='CWUPAC_shadow'>
        <h2 align="center">Control User Access To Their Profile Screen<Br>Email Notifications When User Profile Changed</h2>
        <h5>Version <?php echo esc_html__(CWUPAC_VERSION); ?></h5>
    </div>
    <hr />
</div>
</div>
<?php
}

// ----------------------------------------------------------------------------
//  settings page sidebar content
// ----------------------------------------------------------------------------
function CWUPAC_sidebar() {
	?>
    <h3 align="center">But wait, there's more!</h3>
    <p><b>Need to stop Comment spam?</b> We've got a plugin that does that - install it and comment spam will stop immediately. Very effective. Does not require any other actions or configuration, and your comment form will look the same. It just works! See details here: <a href="https://wordpress.org/plugins/block-comment-spam-bots/" target="_blank" title="Block Comment Spam Bots">Block Comment Spam Bots</a> .</p>
<p><b>Plus these Contact Form spam-blocking plugins:</b></p>
<p><b>If you want to block bots from your contact form</b>, head over to our <a href="https://www.FormSpammerTrap.com" target="_blank" title="FormSpammerTrap - blocks Contact form spammers">FormSpammerTrap</a> site. <i>Works on WP and non-WP sites.</i> Takes a bit of programming, but we can help with that. Full docs and implementation instructions. Just request the free code via the site's Contact form. It's the most powerful and effective way to block Contact Form spammers!</p>
    <p><a href="https://wordpress.org/plugins/formspammertrap-for-comments/" target="_blank"><strong>FormSpammerTrap for Comments</strong></a>: reduces spam without captchas, silly questions, or hidden fields - which don't always work. You can also customize the look of your comment form. Uses the same techniques as our Block Comment Spam Bots plugin. </p>
    <p><a href="https://wordpress.org/plugins/formspammertrap-for-contact-form-7/" target="_blank"><strong>FormSpammerTrap for Contact Form 7</strong></a>: reduces spam when you use Contact Form 7 forms. All you do is add a little shortcode to the contact form.</p>
    <hr />
   <p>For <strong>multisites</strong>, we've got:
    <ul>
        <li><strong><a href="https://wordpress.org/plugins/multisite-comment-display/" target="_blank">Multisite Comment Display</a></strong> to show all comments from all subsites.</li>
        <li><strong><a href="https://wordpress.org/plugins/multisite-post-reader/" target="_blank">Multisite Post Reader</a></strong> to show all posts from all subsites.</li>
        <li><strong><a href="https://wordpress.org/plugins/multisite-media-display/" target="_blank">Multisite Media Display</a></strong> shows all media from all subsites with a simple shortcode. You can click on an item to edit that item. </li>
    </ul>
    </p>
    <hr />
    <p><b>Other Plugins</b></p>
     <p>We've got a <a href="https://wordpress.org/plugins/simple-gdpr/" target="_blank"><strong>CellarWeb Simple GDPR</strong></a> plugin that displays a GDPR banner ('cookie consent') for the user to acknowledge. And it creates a generic Privacy page, and will put that Privacy Page link at the bottom of all pages.</p>
<p><b>An option will do server-side Google Analytics (GA).</b> Did you know what GA is blocked by many ad-blockers - diluting the accuracy of your analytics? This will ensure that every visitor access is captured by GA - and with anonymized information that doesn't store personal information.</p>
<P>For just Google Server Side Analytics - using Googles "UA" analytics code - check out our new <a href="https://wordpress.org/plugins/cellarweb-server-side-analytics/" target="_blank" title="CellarWeb Server Side Analytics"><b>CellarWeb Server Side Analytics</b></a> plugin. Simple and effective - and analytics that are not blocked by ad blockers.</P>
    <p>How about our <strong><a href="https://wordpress.org/plugins/url-smasher/" target="_blank">URL Smasher</a></strong> which automatically shortens URLs in pages/posts/comments?</p>
<p><b>Or one that automatically adds your Affiliate link to all Amazon links - in posts and comments?</b> That's what our Amazolinkentor plugin does, and you can get it <a href="https://wordpress.org/plugins/amazolinkenator/" target="_blank" title="Automatic Affiliate Code Insertion">here</a>.</p>
    <hr />
    <p><strong>They are all free and fully featured!</strong></p>
    <hr />
    <p>I don't drink coffee, but if you are inclined to donate any amount because you like my WordPress plugins, go right ahead! I'll grab a nice hot chocolate, and maybe a blueberry muffin.  Maybe another bag of Cherry Jelly Belliees. And a nice <a href="https://wordpress.org/plugins/simple-cwssa/#reviews" target="_blank" title="CellarWeb Server Side Analytics Plugin Reviews page">review on the plugin page</a> is always appreciated! Or just contact us at <a href="https://cellarweb.com/contactus/" target="_blank">https://cellarweb.com/contactus/</a>. </p>
    <div align="center">
        <?php CWUPAC_donate_button();?>
    </div>
    <p align='center'><b>Thanks!  <a href="https://www.RichardHellewell.com" target="_blank" title="Richard Hellewell author site">Richard Hellewell</a>, somewhere opposite Mutiny Bay WA.</b></p>
    <hr />
    <p><strong>Privacy Notice</strong>: This plugin does not store or use any personal information or cookies.</p>
<?php
CWUPAC_cellarweb_logo();

	return;
}

// ============================================================================
// footer for settings page
// ----------------------------------------------------------------------------
function CWUPAC_footer() {
	?>
    <hr><h3 align='center' class='CWUPAC_larger_text'><b>Thanks for using our CellarWeb User Profile Access Control plugin!  Tell your friends!</b></h3>
<hr><div style="background-color:#9FE8FF !important; padding:10px;color:black !important; ">
    <p align="center"><strong>Copyright &copy; 2016- <?php echo esc_html__(date('Y')); ?> by Rick Hellewell and <a href="http://CellarWeb.com" title="CellarWeb" >CellarWeb.com</a> , All Rights Reserved. Released under GPL2 license. <a href="http://cellarweb.com/contact-us/" target="_blank" title="Contact Us">Contact us page</a>.</strong></p>
</div>
<hr><br>
<?php
return;
}

// ----------------------------------------------------------------------------
// display the copyright info part of the adminpage
// ----------------------------------------------------------------------------
function CWUPAC_info_bottom() {
	CWUPAC_create_page_button(); // show the create the privacy page button
	// print copyright with current year, never needs updating
	$xstartyear    = "2016";
	$xname         = "Rick Hellewell";
	$xcompanylink1 = ' <a href="http://CellarWeb.com" title="CellarWeb" >CellarWeb.com</a>';
	echo esc_html__('<hr><div style="background-color:#9FE8FF;padding-left:15px;padding:10px 0 10px 0;margin:15px 0 15px 0;">
    <p align="center"><strong>Copyright &copy; ' . $xstartyear . '- ' . date("Y") . ' by ' . $xname . ' and ' . $xcompanylink1);
	echo esc_html__(' , All Rights Reserved. Released under GPL2 license. <a href="http://cellarweb.com/contact-us/" target="_blank" title="Contact Us">Contact us page</a>.</strong></p></div><hr>');
	return;
}

// ----------------------------------------------------------------------------
function CWUPAC_cellarweb_logo() {
	?>
 <p align="center"><a href="https://www.cellarweb.com" target="_blank" title="CellarWeb.com site"><img src="<?php echo esc_html__(plugin_dir_url(__FILE__)); ?>assets/cellarweb-logo-2022.jpg"  width="90%" class="CWUPAC_shadow" ></a></p>
 <?php
return;
}

// ----------------------------------------------------------------------------
// PayPal donation button for settings sidebar (as of 25 Jan 2022)
function CWUPAC_donate_button() {
	?>
<form action="https://www.paypal.com/donate" method="post" target="_top">
    <input type="hidden" name="hosted_button_id" value="TT8CUV7DJ2SRN" />
    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
    <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>

<?php
return;
}

// --------------------------------------------------------------------------------------
// end of profile_functions.php
// --------------------------------------------------------------------------------------

// ----------------------------------------------------------------------------
